### ISSUE TITLE
rerender produces a different output each time

### ISSUE THREAD

**Issue by hgrecco** [conda-forge/conda-smithy#1111]
Please take a look at the following terminal dump (rerender output has been replaced by `...` for brevity). Files are changed everytime I run `rerender` eventhough I do not touch manually any file. And after several times, it returns to the original configuration where it starts again.

```
(build) ➜  mypackage-feedstock git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(build) ➜  mypackage-feedstock git:(master) conda smithy rerender
...
Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15
You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15"

These changes need to be pushed to github!

(build) ➜  mypackage-feedstock git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .appveyor.yml
	deleted:    .ci_support/win_.yaml
	modified:   README.md
	modified:   azure-pipelines.yml

(build) ➜  mypackage-feedstock git:(master) conda smithy rerender
...
Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15
You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15"

These changes need to be pushed to github!

(build) ➜  mypackage-feedstock git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .ci_support/linux_.yaml
	deleted:    .ci_support/osx_.yaml
	deleted:    .travis.yml
	deleted:    .travis/build_steps.sh
	deleted:    .travis/run_docker_build.sh
	deleted:    .travis/run_osx_build.sh
	modified:   README.md
	modified:   azure-pipelines.yml

(build) ➜  mypackage-feedstock git:(master) conda smithy rerender
...	
	Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15
You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15"

These changes need to be pushed to github!

(build) ➜  mypackage-feedstock git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .appveyor.yml
	deleted:    .ci_support/win_.yaml
	modified:   README.md
	modified:   azure-pipelines.yml

(build) ➜  mypackage-feedstock git:(master) conda smithy rerender
...
Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15
You can commit the changes with:

    git commit -m "MNT: Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15"

These changes need to be pushed to github!

(build) ➜  mypackage-feedstock git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    .appveyor.yml
	deleted:    .ci_support/win_.yaml
	modified:   README.md
	modified:   azure-pipelines.yml

(build) ➜  mypackage-feedstock git:(master) conda smithy rerender
...
Re-rendered with conda-build 3.18.7, conda-smithy 3.4.1, and conda-forge-pinning 2019.07.15
No changes made. This feedstock is up-to-date.

(build) ➜  mypackage-feedstock git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean		
```

**Comment by isuruf** [comment]
Can you post the contents of the feedstock?

**Comment by hgrecco** [comment]
**conda-forge.yml**
```
github:
  user_or_org: lantzproject
channels:
  sources:
  - conda-forge
  - hgrecco
  - defaults
  targets:
  - [hgrecco, main]
provider:
  linux: travis
  osx: travis
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None
min_py_ver: '36'
travis:
  secure:
    BINSTAR_TOKEN: yI0iS1YyjpcnqDqw0dSRYccqoAydyymI0N2ZOv/qG4EnuZ9ICbypZkZyEmLWveIoRt1md5Tgfn5IKxIb60jF/gHxllwQanzZ35OEutWhuuhX5JLnMv8bosCKD1qYGPUQwUfdfZliFC+F2k7978AAtqV84dh79u3DCo11GoX7zRpz5476bZXB/CAkSsJrYc3rrM9oQd4PZIRnCc1cv+i+KFvSZg0VIHEkZt/sUgR7G013s2peMb4q/bbzixdw/uCded+310gJhtsY4jtgvEVCXszkf7LDXf2ZtN+wjGCFikzwFGbv/3uBxVERZ+18Vi5yoeAOqsJQuho/TwVxWdAk3CxkK+hGqUZLOO9OY+aDBKo3MewsZG+LHHdc/7DwfyAcMvaduTPHXfkMMH7xBN+6NaW86t7aRrAImfKGiVSROeY0k/tXweWjuYRhjMBL8Mq4e2t8J3opTZ7xpCVM40ENO8TO48uv7mQJqGGcfUOcKu640aRSrbRyETBKewnp44nqplohHuzs1AlCtKoWNnybJbOqh+RA/QUy+yZaDaMIwLdmQyxnal6XZbXbuH/MyFSnSM9ACXGtfgYRBfv6jVMnMc5JVQkp277Hmf5QQAVqml0slQC43gASFzgu5OBMccqzHaY3xE+KDJaE2+o6EYMh/nGn0NEd5mO32dEweLS+5MQ=
appveyor:
  secure:
    BINSTAR_TOKEN: qnTwQiGJBWgaW8Tb+rS3SXRTxJPbZJrEtADGdVzCqFn9SEcoewAV3jA/KOhhunFy
```
**recipe/conda_build_config.yaml**
```
channel_sources:
  - conda-forge,hgrecco,defaults
channel_targets:
  - hgrecco main
```
**recipe/meta.yaml**
```
{% set version = '0.5.2' %}
{% set deps=[
  'https://files.pythonhosted.org/packages/f3/b8/30eacbfefe273628e6039ebf54f57b9f47630391493f9d34650752df9e54/PySignal-1.1.1.tar.gz',
  'https://github.com/pyvisa/pyvisa/archive/1.9.1.zip',
  'https://github.com/pyvisa/pyvisa-py/archive/0.3.1.zip',
  'https://github.com/hgrecco/pint/archive/0.9.zip',
  'https://github.com/hgrecco/pimpmyclass/archive/0.4.3.zip',
  'https://github.com/hgrecco/serialize/archive/0.1.zip',
  'https://github.com/hgrecco/stringparser/archive/0.5.zip',
  'https://github.com/lantzproject/cutelog/archive/patched_stable.zip',
  ]
%}

package:
  name: lantzfull
  version: {{ version }}

build:
  number: 1
  skip: True  # [py2k]
  script:
    {% for dep in deps %}
    - '{{ PYTHON }} -m pip install {{ dep }}'
    {% endfor %}
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz-core/archive/0.5.3.zip'
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz-drivers/archive/0.5.2.zip'
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz-qt/archive/0.5.3.zip'
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz-sims/archive/0.5.2.zip'
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz-ino/archive/0.5.2.zip'
    - '{{ PYTHON }} -m pip install https://github.com/lantzproject/lantz/archive/0.5.2.zip'

requirements:
  host:
    - python >=3.6
    - pip
    - pyqt >=5.6
  run:
    - arduino-cli
    - pyqt >=5.6
    - python >=3.6
    - pyyaml
    - qtpy

about:
  home: https://github.com/lantzproject/lantz
  license: BSD
  summary: 'Instrumentation framework'
  description: |
    Lantz is an automation and instrumentation toolkit with a clean, well-designed and consistent interface.
    It provides a core of commonly used functionalities for building applications that communicate with
    scientific instruments allowing rapid application prototyping, development and testing.
```
