### ISSUE TITLE
Linter crashes under certain conditions

### ISSUE THREAD

**Issue by tim-werner** [conda-forge/conda-smithy#1231]
Issue:

The linter (version 3.6.8) crashes with:

```
File lint_recipe.py, line 485, in lintify
constraint = req.split(" ", 1)[1]
IndexError: list index out of range
```

This happens when non noarch build is triggered and the run section contains packages that start with `python` (e.g. python-dateutil) that do not have version contraints. 

Minimal example `meta.yaml`:
```
{% set name = "testapp" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/apache/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 194n4140184140194124914u1n0914j1041j04104014m1401420411244210410
  - url: https://raw.githubusercontent.com/apache/{{ name }}/master/LICENSE.txt
    sha256: 832u5y3285w89y537w05w49572j5nnm151591515213532mnn141249000090914

build:
  # noarch not set
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or py2k]
  entry_points:
    - superset = superset.bin.superset:cli

requirements:
  build:
    - nodejs
  host:
    - python
    - pip
  run:
    - python-dateutil # without version
```
