### ISSUE TITLE
Setting up a custom image

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1332]
I am trying to set up a custom docker image (`linux-anvil-cos7-x86_64`) but `regenerate` doesn't take it into account.

`conda-forge.yml`:

```yaml
docker:
  fallback_image: linux-anvil-cos7-x86_64
```

After `regenerate`, `./scripts/run_docker_build.sh` contains:

```bash
if [ -z "${DOCKER_IMAGE}" ]; then
    SHYAML_INSTALLED="$(shyaml -h || echo NO)"
    if [ "${SHYAML_INSTALLED}" == "NO" ]; then
        echo "WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Falling back to linux-anvil-cos7-x86_64"
        DOCKER_IMAGE="linux-anvil-cos7-x86_64"
    else
        DOCKER_IMAGE="$(cat "${FEEDSTOCK_ROOT}/.ci_support/${CONFIG}.yaml" | shyaml get-value docker_image.0 linux-anvil-cos7-x86_64 )"
    fi
fi
```

but `..azure-pipelines/azure-pipelines-linux.yml` contains:

```yaml
jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      linux_:
        CONFIG: linux_
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
    maxParallel: 8
  timeoutInMinutes: 360
```

which take precedence over the `run_docker_build.sh`.

I could edit manually `azure-pipelines-linux.yml` but it would be erased at each new `regenerate`. Any idea?

**Comment by isuruf** [comment]
You'll need to add the `docker_image` in `recipe/conda_build_config.yaml` or use a custom version of `conda_build_config.yaml` from `conda-forge-pinning`.

This fallback should be deleted IMO.

**Comment by hadim** [comment]
I forgot to mention that I already tried `docker_image` in `recipe/conda_build_config.yaml` but `regenerate` fails with:

```
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_build/variants.py", line 277, in combine_specs
    log_output=log_output)
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_build/variants.py", line 252, in _combine_spec_dictionaries
    spec_source))
ValueError: variant config in /home/hadim/Drive/Documents/InVivo/Platform/Forge/invivobase-feedstock/recipe/conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.
```

```yaml
channel_sources:
  - channel_1, conda-forge, channel_2, channel_3, default

channel_targets:
  - channel_1, main

docker_image:
  - condaforge/linux-anvil-cos7-x86_64

```
