### ISSUE TITLE
Add a private conda channel to conda forge config (for private forge)

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1337]
In `conda-forge.yml`: 

```yaml
channels:
  sources:
    - private_channel, conda-forge, channel_2, channel_3, default
  targets:
    - private_channel main
```

During CI builds, downloading from `private_channel` is not possible since packages are private.

I know it's possible in an `environment.yml` file to specify a token:

```yaml
channels:
  - t/<MY_TOKEN>/private_channel
  - conda-forge
  - channel_2
  - channel_3
```

What would the best way to do that in a private forge?

```yaml
channels:
  sources:
    - t/$ANACONDA_TOKEN/private_channel, conda-forge, channel_2, channel_3, default
  targets:
    - private_channel main

docker:
  run_args: "-e ANACONDA_TOKEN"
```

Question is how to evaluate `t/$ANACONDA_TOKEN/private_channel` to `t/<MY_TOKEN>/private_channel`.
