### ISSUE TITLE
conda-forge-linter fails when multiple licenses types are provided

### ISSUE THREAD

**Issue by carterbox** [conda-forge/conda-smithy#1610]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```yaml
about:
  home: https://github.com/ilanschnell/bsdiff4
  license:
    - BSD
    - CC
  license_file:
    - LICENSEA
    - LICENSEB
  summary: binary diff and patch using the BSDIFF4-format
```

In a recipe you are allowed to specify multiple license files, but only one "type" of license?  This package in staged-recipes https://github.com/conda-forge/staged-recipes/pull/16339 contains multiple sources with different licenses, so in theory we should be listing the different types of license in the metadata, but the linter raises and error if you use a YAML list to enumerate multiple license types. e.g. something like this:

```yaml
about:
  home: http://dsi-studio.labsolver.org
  license: CC BY-NC-SA 4.0
  license_family:
    - CC
    - BSD
  license_file: ${PREFIX}/LICENSE
  summary: "Diffusion MRI Tractography Tool"
  doc_url: https://dsi-studio.labsolver.org/
```
Gets this response:
> Failed to even lint the recipe, probably because of a conda-smithy bug 😢. This likely indicates a problem in your meta.yaml, though. To get a traceback to help figure out what's going on, install conda-smithy and run conda smithy recipe-lint . from the recipe directory.

### Installed packages

```shell
conda-forge-linter
```

### Environment info

```shell
conda-forge-linter
```
