### ISSUE TITLE
Rendering with common "{{ native }}pkg" pattern does not apply pinning

### ISSUE THREAD

**Issue by mbargull** [conda-forge/conda-smithy#1680]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Rendering with the common
```yaml
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
...
requirements:
  host:
    - {{ native }}pkg
```
pattern as found in `r-*` feedstocks does not apply the pinnings for `pkg`.

See the sequence of:
 - https://github.com/conda-forge/r-xml-feedstock/pull/33#issuecomment-1282322938
 - https://github.com/conda-forge/r-xml-feedstock/pull/33/commits/62becae06e176ea60fd2fb6186af499459b16746
 - https://github.com/conda-forge/r-xml-feedstock/pull/33/commits/79490e9c7bbb1ab9a3ed5f913446fded7589a5f6

### Installed packages

```shell
conda-forge-webservices issuing:
MNT: Re-rendered with conda-build 3.22.0, conda-smithy 3.21.2, and conda-forge-pinning 2022.10.18.09.43.36
```

### Environment info

```shell
conda-forge-webservices issuing:
MNT: Re-rendered with conda-build 3.22.0, conda-smithy 3.21.2, and conda-forge-pinning 2022.10.18.09.43.36
```
