### ISSUE TITLE
Can conda-smithy leverage `load_file_data()` like conda-build?

### ISSUE THREAD

**Issue by d33bs** [conda-forge/conda-smithy#1814]
### Comment:

Thank you for the great documentation and efforts surrounding this project! In reading and developing a Conda recipe for a Python package I discovered recently that [`load_file_data()` which is mentioned in the conda-build documentation](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files) doesn't seem to be compatible with conda-smithy. When attempting to leverage that functionality through a recipe, I receive an error from conda-smithy: `jinja2.exceptions.UndefinedError: 'load_file_data' is undefined`.

As a relative newcomer to the Conda environment, I wanted to reach out and ask whether the `load_file_data()` capability was something I could enable or leverage through conda-forge related package distribution. Generally my goal is to "single-source" metadata from the software's `pyproject.toml` file, enabling the reference of informational data from a single place instead of duplicating it in multiple files or locations. If I can't do this, any guidance on what features or capabilities I should constrain my development to would be much appreciated! Thanks in advance for any help or suggestions on this 🙂 .

Example `meta.yaml` concerning what I'd like to use through conda-forge (and check via conda-smithy):

```yaml
{% set pyproject = load_file_data('pyproject.toml', from_recipe_dir=true) %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}

package:
  name: {{ poetry.get('name').lower() }}
  version: {{ poetry.get('version') }}
...
```

Related PR which might yield further insight: https://github.com/conda-forge/staged-recipes/pull/24816
