### ISSUE TITLE
add lint for run_exports outside of a build section

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1857]
In some cases, run_exports outside of build sections are ignored in multioutput recipes. This syntax

```yaml
outputs:
  - name: blah
    run_exports:
     - blah
```

is the main issue. 

See this PR https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/103.

We should lint for this syntax and make sure recipes do not use it.

**Comment by carterbox** [comment]
The correct placement would be

```yaml
outputs:
  - name: blah
    build:
      run_exports:
       - blah
```

**Comment by isuruf** [comment]
Both are fine, except when you have
```yaml
outputs:
  - name: blah
    run_exports:
     - blah
     build:
       some_other_option: value
```
