### ISSUE TITLE
Allow customizations of shellcheck linter

### ISSUE THREAD

**Issue by mbargull** [conda-forge/conda-smithy#1965]
### Comment:

As is, the `shellcheck` option unconditionally runs
```sh
shellcheck --enable=all --shell=bash --exclude=SC2154 "${RECIPE_DIR}"/*.sh
```
if enabled.
There are cases in which one would want to customize these options, e.g., in case of activation scripts it can make sense to use `--shell=sh` to lint for broader than Bash compatibility.

One flexible solution could be to turn the option from a Boolean switch to something akin to this:
```yaml
shellcheck:
  - files: 'build.sh'
    args: [--enable=all, --shell=bash, --exclude=SC2154]
  - files: '*activate-*.sh'
    args: [--enable=all, --shell=sh]
```
