### ISSUE TITLE
Rerendering rattler recipe drops project links

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2058]
After having done a basic [conversion](https://github.com/conda-forge/zlib-feedstock/pull/83) of zlib to rattler (using `conda-recipe-manager` following this [blog](https://prefix.dev/blog/rattler_build_on_conda_forge) + manual fixes), the about section changed from

```yaml
about:
  home: http://zlib.net/
  license: Zlib
  summary: Massively spiffy yet delicately unobtrusive compression library
  license_family: Other
  license_file: LICENSE
  description: |
    zlib is designed to be a free, general-purpose, lossless data-compression
    library for use on virtually any computer hardware and operating system.
  doc_url: http://zlib.net/manual.html
  dev_url: https://github.com/madler/zlib
```
to
```yaml
about:
  license: Zlib
  summary: Massively spiffy yet delicately unobtrusive compression library
  license_file: LICENSE
  description: |
    zlib is designed to be a free, general-purpose, lossless data-compression
    library for use on virtually any computer hardware and operating system.
  homepage: http://zlib.net/
  repository: https://github.com/madler/zlib
  documentation: http://zlib.net/manual.html
```

I don't really mind how the keys are named (e.g. `repository` vs. `dev_url`), but smithy needs to take into account the right keys to populate the `README.md`. After having hacked around #2057, I see the following diff in the README currently:
```diff
--- a/README.md
+++ b/README.md
@@ -3,20 +3,15 @@ About zlib-feedstock

 Feedstock license: [BSD-3-Clause](https://github.com/conda-forge/zlib-feedstock/blob/main/LICENSE.txt)

-Home: http://zlib.net/
+

 Package license: Zlib

 Summary: Massively spiffy yet delicately unobtrusive compression library

-Development: https://github.com/madler/zlib
-
-Documentation: http://zlib.net/manual.html
-
 zlib is designed to be a free, general-purpose, lossless data-compression
 library for use on virtually any computer hardware and operating system.

-
 Current build status
 ====================
```
