### ISSUE TITLE
improve conda linting message: No valid build backend found

### ISSUE THREAD

**Issue by JohannesBuchner** [conda-forge/conda-smithy#2103]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I got this message:

"Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (recipe/meta.yaml) and found it was in an excellent condition.
I do have some suggestions for making it better though...

For recipe/meta.yaml:

    No valid build backend found for Python recipe for package ultranest using pip. Python recipes using pip need to explicitly specify a build backend in the host section. If your recipe has built with only pip in the host section in the past, you likely should add setuptools to the host section of your recipe.
"

There are many technical terms specific to conda and python packaging here, such as "build backend" and "host section".
The text writes "in the host section" implying that I have one in recipe.yaml. I do have requirements->host, am I supposed to write it there? https://github.com/conda-forge/ultranest-feedstock/blob/main/recipe/meta.yaml

Like many maintainers, I do not spend all day working on conda recipes and do not keep its documentation and terminology in my forehead. I just use it to get things done. It would be very helpful to design the linter to either a) add a suggested snippet of the relevant recipe section to such messages, b) add a link to an example that addresses this message, c) add a link to the conda documentation where the problem and solution is explained.

### Installed packages

N/A

### Environment info

N/A

**Comment by ocefpaf** [comment]
> There are many technical terms specific to conda and python packaging here, such as "build backend" and "host section".
The text writes "in the host section" implying that I have one in recipe.yaml. I do have requirements->host, am I supposed to write it there?

Correct.

> Like many maintainers, I do not spend all day working on conda recipes and do not keep its documentation and terminology in my forehead. 

Any improvements to the message/docs are welcomed. The host was easy to find. Backend is python specific, not conda, and foryour package it seems to be setuptools. See https://github.com/JohannesBuchner/UltraNest/blob/fbde672781762ef01aa24b46bdd01c614e0b0005/pyproject.toml#L3

**Comment by beckermr** [comment]
Very happy to help make things clearer! One question about that. The message says 

"If your recipe has built with only pip in the host section in the past, you likely should add setuptools to the host section of your recipe." 

The idea was to provide specific instructions for the most common case. What was confusing about this for you? 

We maintain conda recipes so much that we cannot tell, as you say above, and so any help in making it clearer would be very welcome.

Thank you!

**Comment by JohannesBuchner** [comment]
Thanks for the question.

My recipe has a build section:

```
build:
  number: 1
  # may need to later add "skip: True  # [win]" to disable Windows.
  script_env:
    - MPLBACKEND=agg
  skip: true  # [py<30 or python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install . -vv
```
so my first instinct was that I should add it there.

There is a requirements section which has a host sub-section:
```
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    # cython project, so need a compiler
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - python
    - pip
    - cython
    - numpy
    - pytest-runner
```

I would suggest changing "you likely should add setuptools to the host section of your recipe"
to "you likely should add setuptools to the [host section within the requirements section](https://conda-forge.org/docs/maintainer/adding_pkgs/#use-pip) of your recipe"

Having the link to the docs would make it clear.

It is also confusing because both sub-sections and sections are called "sections" in https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host so my first instinct was that I would have to add another section that I had never heard of.

I would suggest having a look at the other rules of the linter and adding pointers to the documentation to those as well. It just saves the maintainer time to not have to come up with the right google keywords and find the right page, when the linter already can narrow it down and point to the documentation or upgrade notes explaining the context.

Thank you for your consideration.

**Comment by clbarnes** [comment]
I am also hitting the same message with the same question.

My recipe was largely auto-generated by rattler-build (grayskull didn't work due to missing conda-recipe-manager). I am relying on CI for the lints as build-locally.py also doesn't work ("User-provided OSX_SDK_DIR is not writeable for current user!").

For reference, I am packaging transformnd: https://github.com/clbarnes/transformnd/ 

```yaml
# staged-recipes:recipes/transformnd/recipe.yaml
...

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.12.10,<0.13.0
    - pip
  ...
```

`requirements.host` is a sequence of dependencies. As far as I can tell, there is no way to specify the build backend there, only to specify a list of packages, one of which should provide the build backend, which is itself configured in a pip-discoverable way:

```toml
# transformnd:pyproject.toml
...

[build-system]
requires = ["uv-build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
```

If the requirement is for the backend-providing package to be listed there, the message could read something like

> No valid build backend found for Python recipe for package {{ package }} using pip. Python recipes using pip in their `build.script` need to explicitly list the package which provides the build backend in the `requirements.host` sequence. If your recipe was built with only `pip` in the `requirements.host` sequence in the past, you likely should add `setuptools` to the `requirements.host` sequence of your recipe.

However, I have done this already so that doesn't seem to be the requirement. Based on the current message, I would expect some explicit `build_backend` key in the configuration; maybe something like

```yaml
# staged-recipes::recipes/transformnd/recipe.yaml
...

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  build_backend: uv_build  # <---------------- new field mirroring pyproject.toml:build-system/build-backend
  noarch: python
```
