### ISSUE TITLE
Support for nested conditionnal selectors in v2 recipe

### ISSUE THREAD

**Issue by olivier-roussel** [conda-forge/conda-smithy#2109]
### Comment:

I recently faced some cases where it seemed relevant and more readable to use nested `it / then / else` in new recipe (rattler) format, instead of one-lining the expression. See here for a concrete case : https://github.com/conda-forge/eigenpy-feedstock/blob/5f141210cc57dc0c8cfbe9db4d7e59c3cd3f6347/recipe/recipe.yaml#L36-L48
It seems that `rattler build` supports such nested selectors, but `conda smithy` does not. 
Here a simpler reproducible example that fails with conda smithy linter:
```yaml
  - if: arm64
    then:
      - if: linux
        then: 
          - foo
    else:
      - notfoo
```
I guess the first question raised here before going further is: should it be supported in the new recipe v2 standard ?
