### ISSUE TITLE
Linting CBC does not diagnose wrong usage correctly

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2152]
The following file as `conda-forge.yml` yields a clean slate
```yaml
build_platform:
  wrong: a
os_version:
  wrong: b
provider:
  wrong: c
```
despite the fact that, based on `schema.py` (or at least the obvious intent there), it should fail:
https://github.com/conda-forge/conda-smithy/blob/2b18d8dd41de178e30506e420022b2a5590a4acf/conda_smithy/schema.py#L548-L563

All three of those are using pydantic's `create_model`, which I presume is not working as intended here.
