### ISSUE TITLE
ENH: Allow ignoring `python_min` hints

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2170]
Some feedstocks need to opt-out of the test pins for `python_min`, for example due to being used elsewhere as a `downstreams:` test against other python versions (c.f. https://github.com/conda-forge/conda-forge.github.io/pull/2387, https://github.com/conda-forge/conda-smithy-feedstock/pull/331, https://github.com/conda-forge/setuptools-feedstock/pull/371).

Given this reality, we shouldn't force those feedstocks to live with linter warnings in perpetuity, but give them a way to silence the linter. In https://github.com/conda-forge/conda-smithy/pull/2090, the following mechanism was introduced
```yaml
linter:
  skip:
    - lint_noarch_selectors
```

This could easily be extended to allow
```yaml
linter:
  skip:
    - hint_python_min
```
