### ISSUE TITLE
Linting for v1 recipes fail cuz of false positive (CFEP 25)

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#2183]
See https://github.com/conda-forge/plip-feedstock/pull/12#issuecomment-2535980043 for context.

In short, the below recipe triggers a lint error from the bot (see above PR):

```yaml
requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - lxml >=4.2.1
    - numpy >=1.13.3
    - openbabel >=3.0.0
  run_constraints:
    - ImageMagick >=7.0
    - pymol-open-source >=2.3.0

tests:
  - python:
      imports:
        - plip
      python_version: ${{ python_min }}
      pip_check: false # it fails at detecting openbabel. see https://github.com/conda-forge/openbabel-feedstock/issues/49
  - script:
      - plip --help
    requirements:
      run:
        - python ${{ python_min }}
```

ping @beckermr
