### ISSUE TITLE
BUG: false negative for CFEP-25 linting

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2188]
Found a situation where [there's](https://github.com/lucascolley/scipy-stubs-feedstock/blob/0f60173aa1e5e035bdafa8fd7014df572cd5a476/recipe/meta.yaml) an output
```yaml
  - name: scipy-typed
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - scipy =={{ scipy_version }}
        - {{ pin_subpackage('scipy-stubs', exact=True) }}
    test:
      requires:
        - basedmypy
      imports:
        - scipy
```
and yet, the linter (from 3.45.0) says it's fine.
