### ISSUE TITLE
cfep-25 false positive: v1 recipe and python only test

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#2209]
Consider the following recipe:

```yaml
context:
  name: mypackage
  version: 1.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mypackage-${{ version }}.tar.gz
  sha256: c792c023400ce8f9b8e708f8bdf3c76733d6979608a83870965e7622dc6eb4c4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy

tests:
  - python:
      imports:
        - mypackage
      python_version: ${{ python_min }}.*

about:
  summary: a summary
  license: MIT
  license_file: LICENSE
  homepage: https://conda-forge.org/

extra:
  recipe-maintainers:
    - hadim
```

Linter output

```
recipe/ has some lint:
  The feedstock has no `.ci_support` files and thus will not build any packages.
recipe/ also has some suggestions:
  `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
       - For the `test.requires` section of the recipe, you should usually use `python ${{ python_min }}` for the `python` entry.
       - If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
```

(you can safely ignore the ".ci_support" error here)

---

It's because the linter is not aware of `tests[].python.python_version` that has been recently introduced in rattler-build.
