### ISSUE TITLE
False positive in `lint_recipe_name`

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/conda-smithy#2224]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

In `lint_recipe_name`, you can get a false positive with the following recipe:

```yml
# recipe.yaml
context:
  version: '1.20.0'

# Note: This recipe is specifically designed to work well with the autotick bot.
# Also refer to https://github.com/conda-forge/rust-feedstock/blob/main/recipe/meta.yaml.
package:
  name: ${{ polars_variant }}
  version: ${{ version }}

# ...
```

You need to specify `polars_variant` in `conda_build_config.yaml`:

```yml
polars_variant:
  - polars  # [not ppc64le]
  - polars-lts-cpu
  - polars-u64-idx  # [not ppc64le]
```

this occurred in https://github.com/conda-forge/polars-feedstock/pull/303

https://github.com/conda-forge/conda-smithy/blob/fcbd049cb268eb5c8732f4b5e498bf011398f5ea/conda_smithy/linter/conda_recipe_v1_linter.py#L132-L140

### Installed packages

```shell
-
```

### Environment info

```shell
-
```
