### ISSUE TITLE
BUG: v1 recipe fails to rerender due to rattler false positive

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2231]
In the torchaudio feedstock, we have the following
```yaml
build:
  number: ${{ build_number }}
  skip:
    - win
    - match(cuda_compiler_version, "11.8") and aarch64
```
This looks reasonable (and used to work fine), but rerendering the recipe with new rattler-build now fails with:
```
Error:
  x failed to render Jinja expression: syntax error: Bad syntax for `spec`: missing range specifier for '11.8'. Did
  | you mean '==11.8' or '11.8.*'? (in <expression>:1)
    ,-[30:7]
 29 |     - win
 30 |     - match(cuda_compiler_version, "11.8") and aarch64
    :       ^^^^^^^^^^^^^^^^^^^^^^^^|^^^^^^^^^^^^^^^^^^^^^^^
    :                               `-- here
 31 |   string: ${{ string_prefix }}py${{ python | version_to_buildstring }}h${{ hash }}_${{ build_number }}
    `----
```

It's IMO completely misplaced to enforce this kind of spec strictness in boolean comparisons. conda-forge's pinning is simply "11.8", we should be able to compare to that, exactly.

CC @wolfv @baszalmstra
