### ISSUE TITLE
Removing `=` pins as hinted breaks grpc recipe

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2262]
The `=` pins in 
```yaml
  - name: grpcio-tools
    [..]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - grpcio ={{ version }}=*_{{ PKG_BUILDNUM }}
        - python
        - cython
        - pip
        - setuptools
      run:
        - grpcio ={{ version }}=*_{{ PKG_BUILDNUM }}
        - python
        - protobuf
        - setuptools
```
cause the following linter [warning](https://github.com/conda-forge/grpc-cpp-feedstock/pull/384#issuecomment-2692389714) (original formatting, which seems broken too)
> * In section host: `grpcio =1.68.2=*_PKG_BUILDNUM
> 
> * In section run: `grpcio =1.68.2=*_PKG_BUILDNUM Requirements spec fields should always be space-separated to avoid known issues in conda-build. For example, instead of `name =version=build`, use `name version build`.

However, actually removing the pins breaks the build as follows ([logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1188542&view=results))
```
conda_build.exceptions.RecipeError: Mismatching hashes in recipe. Exact pins in dependencies that contribute to the hash often cause this. Can you change one or more exact pins to version bound constraints?
Involved packages were:
Mismatching package: grpcio (id py313h1474e93_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py313h1474e93_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py310h56e06c5_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py310h56e06c5_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py39hd7d1cbf_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py39hd7d1cbf_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py311h9789449_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py311h9789449_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py312hacea422_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
Mismatching package: grpcio (id py312hacea422_0); dep: grpcio 1.68.2 *_0; consumer package: grpcio-tools
```

CC @jaimergp @beckermr
