### ISSUE TITLE
Allow specifying override channel targets on a per-output basis

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/conda-smithy#2263]
### elevator pitch

In `conda-forge.yml`, provide a way to influence `channel_targets` on a per-output basis.

## references
- https://github.com/conda-forge/admin-requests/pull/1412#issuecomment-2692770863
- https://github.com/conda/ceps/pull/102#issuecomment-2517864942

## schema strawman
Not sure where this would land, but...

```json
{
  "properties": {
    "output_channel_targets": {
      "type": "object",
      "description": "overrides to `conda_build_config.yaml`'s `channel_targets` by output name", 
      "additionalProperties": {
        "description": "where to upload an output based on output name, which may include `*` wildcards",
        "default": null,
        "anyOf": [
          {"type": "null", "description": "use `channel_targets` unchanged"},
          {"type": "boolean", "const": false, "description": "skip uploading this output"},
          {"type": "string", "description": "always upload this output to `conda-forge/label/{value}`"},
        ]
      }
    }
  }
}
```

Extending the `oneOf` above, one could imagine some "well-known" labels to give some
more meaning to the packages there:

```json
  "oneOf": [
    {"type": "string", "const": "tests", "description": "well-known channel for test-only packages, available for `downstream` tests"},
    {"type": "string", "const": "docs", "description": "well-known channel for html-based versioned documentation, e.g. `/var/www/html/{feedstock-name}/{version}/index.html`"},
  ]
```

For example, to upload unvendored tests, a built documentation site, and skip
some weird build-time intermediate:

```yaml
output_channel_targets:
 # implicitly
 # foo: {{ channel_targets }}
 foo_tests: tests                       # ship to `conda-forge/label/tests`
 foo-docs: docs                         # ship to `conda-forge/label/docs`
 _foo_some_intermediate_garbage: false  # don't ship, ever
```
