### ISSUE TITLE
BUG: false positives for hint against `=` in pins

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#2272]
The new rule about pinning without `=` has a false positive about `- python >= 3.8` (e.g. in the pinning repo [currently](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/18d4568c3d17d1bc4b2dc115a45577994d1ec9b9/recipe/meta.yaml#L26)):

> In section test: python >= 3.8 Requirements spec fields should always be space-separated to avoid known issues in conda-build. For example, instead of name =version=build, use name version build`.

CC @jaimergp

**Comment by jaimergp** [comment]
There should no space between `>=` and `3.8`.

**Comment by h-vetinari** [comment]
> There should no space between `>=` and `3.8`.

Sure, but that's a separate issue. We can add a lint for this, but we should not show a misleading hint about removing relational operators in such a case

**Comment by h-vetinari** [comment]
Another case that causes spurious warnings seems to be double-spaces
```yaml
  run_constrained:
    - conda-verify  >=3.1.0
```
See https://github.com/conda-forge/conda-build-feedstock/pull/249

**Comment by beckermr** [comment]
more here: https://github.com/conda-forge/stackvana-feedstock/pull/218#issuecomment-2741309185

**Comment by jaimergp** [comment]
Added https://github.com/conda-forge/conda-smithy/pull/2282

**Comment by h-vetinari** [comment]
We still have problems with stuff like `pin_subpackage()`, e.g. the following output
```yaml
  - name: flang-rt
    requirements:
      host:
        - {{ pin_subpackage("libflang-rt", exact=True) }}   # [linux]
        - {{ pin_subpackage("flang-rt_" ~ target_platform, exact=True) }}
      run:
        - {{ pin_subpackage("libflang-rt", exact=True) }}   # [linux]
        - {{ pin_subpackage("flang-rt_" ~ target_platform, exact=True) }}
```
produces the following linter warning

> For **recipes/flang-rt/meta.yaml**:
> * ℹ️ flang-rt output has some malformed specs:
>   * In section host: `subpackage_pin flang-rt_linux-64
>   * In section run: `subpackage_pin flang-rt_linux-64 Requirement spec fields should match the syntax `name [version [build]]`to avoid known issues in conda-build. For example, instead of `name =version=build`, use `name version.* build`. There should be no spaces between version operators and versions either: `python >= 3.8`should be`python >=3.8`.

Formatting is still busted too.
