### ISSUE TITLE
Linter should warn on `python_min` usage in non-`noarch` recipes

### ISSUE THREAD

**Issue by dhmjhu** [conda-forge/conda-smithy#2277]
### Comment:

I have a suggestion based on my experience updating `spikeinterface-feedstock` (which is a pure Python package).

Initially, the recipe had `noarch: python`. After removing that (see conda-forge/spikeinterface-feedstock#6), the linter warned that there should be no version constraints on `python`, so I [removed those](https://github.com/conda-forge/spikeinterface-feedstock/compare/d40f96e01372dab419043e9ad3c932ecfde543fd..a36d92bcd7eddadd63feb7fc1f4cbe3be796004e) as well. However, I [left `python {{ python_min }}` in the `host` section](https://github.com/conda-forge/spikeinterface-feedstock/blob/a36d92bcd7eddadd63feb7fc1f4cbe3be796004e/recipe/meta.yaml#L18).

The linter did not report any problems, but the build later failed with:
```text
conda_build.exceptions.CondaBuildUserError: Failed to render jinja template in spikeinterface-feedstock\recipe\meta.yaml:
'python_min' is undefined
```

As I understand [CFEP-25](https://github.com/conda-forge/cfep/blob/main/cfep-25.md), `python_min` is only valid for `noarch: python` packages. Shouldn't the linter warn about `python_min` being used in a non-`noarch` package?

The proposed warning might look something like:
```text
recipe has some lint:
  Non noarch packages should not use python_min.
```

Unless there's a valid use case for `python_min` in non-`noarch` packages (which I may have missed), this check would help avoid rendering failures.

This applies to both the GitHub bot and running `conda smithy lint` locally. For reference, my local (Windows) environment has:
```text
conda                     24.11.2         py312h2e8e312_0    conda-forge
conda-forge-pinning       2025.01.02.18.17.44      hd8ed1ab_0    conda-forge
conda-smithy              3.45.1          win_pyhef2d1d4_0    conda-forge
```

Would it make sense to add this linter check? Or is there a reason `python_min` should be allowed in non-`noarch` recipes?

(This whole situation arose because `noarch` packages can't use selectors, which I am using to specify the correct version of NumPy per [upstream](https://github.com/SpikeInterface/spikeinterface/blob/36e54b7a5671b7316ba147eb6e931573b3d38044/pyproject.toml#L23-L24). If there's another way to accomplish that, please let me know!)

**Comment by bollwyvl** [comment]
In this particular instance, overloading `python_min` in `conda_build_config.yaml` works to appease the linter and get back to two (instead of `{os * arch * py}`) builds... 

<details><summary>some untested thoughts...</summary>

```yaml
# conda_build_config.yaml
python_min:
  - "3.11" # update (m)anually to keep in sync with the rest of the ecosystem
  - "3.13"
```

... then

```yaml
# meta.yaml
#...
build:
  noarch: python
# ...
requirements:
  host:
    - python {{ python_min }}.*
    # ...
  run:
    - python >={{ python_min }}
    - numpy >={{ "2.0.0" if python_min == "3.13" else "1.20" }}
  run_constraints:
    - python {{ "<3.13" if python_min != "3.13" else "" }}
# ...
```

... then a re-render.

Similarly, in a v1 recipe, the linter still prefers them to be done up-front rather than the more structural `if/then/else`:

```yaml
# recipe.yaml
context:
  # ...
  numpy_min: ${{ "2.0.0" if python_min == "3.13" else "1.2.0" }}
  python_max: ${{ "" if python_min == "3.13" else "3.13" }}
requirements:
  run:
    - python >=${{ python_min }
    - numpy >=${{ numpy_min }}
  run_constrained:
    - python ${{ "<" ~ python_max if python_max }}
```

</details>
