### ISSUE TITLE
False positive "noarch packages can't have selectors" in v1-recipes

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/conda-smithy#2337]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

```yml
context:
  name: pixi-pycharm
  version: "0.0.8"
  build: 1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/pavelzw/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: a7b9294417d7857814eb5e7d4731657fcc1481c903c486d0aeaa2cd356f4cf58

build:
  string: ${{ 'win' if build_win else 'unix' }}_h${{ hash }}_${{ build }}
  noarch: generic
  script:
    - if: build_win
      then:
        - mkdir -p $PREFIX/libexec
        - cp conda $PREFIX/libexec/conda.py
        - sed -i '1d' $PREFIX/libexec/conda.py
        - cp conda.bat $PREFIX/libexec/conda.bat
      else:
        - mkdir -p $PREFIX/libexec
        - echo "#!$PREFIX/bin/python" > $PREFIX/libexec/conda
        - cat conda >> $PREFIX/libexec/conda
        - sed -i '2d' $PREFIX/libexec/conda
  number: ${{ build }}

requirements:
  build:
    - sed
  run:
    - if: build_win
      then: __win
      else: __unix
    - python >=3.8

tests:
  - package_contents:
      files:
        - if: build_win
          then:
            - libexec/conda.py
            - libexec/conda.bat
          else:
            - libexec/conda

about:
  homepage: https://pixi.sh/latest/integration/editor/jetbrains
  documentation: https://pixi.sh/latest/integration/editor/jetbrains
  summary: Conda shim for PyCharm that proxies pixi
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/pavelzw/pixi-pycharm

extra:
  recipe-maintainers:
    - pavelzw
```

```yml
build_win:
- true
- false
```

The selectors are only referencing things from `conda_build_config.yaml` which should be excluded.

Happens in https://github.com/conda-forge/pixi-pycharm-feedstock/pull/10

### Installed packages

```shell
-
```

### Environment info

```shell
-
```
