### ISSUE TITLE
Is there a way to specify a custom user/channel to upload packages to?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-smithy#801]
Great work on these tools. They really help deploying packages.

I would like to deploy packages to my own channel using conda-smithy rendered recipes.

currently I have to change the line that has the command `upload_or_check_non_existance` after I rerender my recipe. Is this necessary? is there a flag I can set in `conda-forge.yml` to specify my user?

**Comment by isuruf** [comment]
Add the following to `conda-forge.yml` and rerender.
```
channels:
  sources: [mychannel, conda-forge, defaults]
  targets:
    - [mychannel, mylabel]
```

`sources` line is necessary only if you want to pull in packages from your channel for the building of the package.
