### ISSUE TITLE
linter: generalize not empty tests to recipes with multiple outputs

### ISSUE THREAD

**Issue by sdvillal** [conda-forge/conda-smithy#833]
The linter currently flag with no-test recipes with multiple outputs and non-empty test per output, but not common tests. I think it should instead just check there is no output without test. 

See: https://github.com/conda-forge/x264-feedstock/pull/19#issuecomment-404994818

Example in there:

```yaml
# All outputs include some tests
outputs:
  - name: x264
    ...
    test:
      commands:
        - x264 --help                                          # [unix]

  - name: libx264
    ...
    test:
      commands:
        - test -f ${PREFIX}/include/x264.h                     # [unix]

# There are no tests here because they are not needed
```
