### ISSUE TITLE
rerendering when subpackages depend on `compiler('cxx')`

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/conda-smithy#930]
When subpackages have build-time dependencies on compilers, but not the top-level recipe, the rerendering of the recipe does not produce all the usual variantes for compiled packages.

A practical fix is to add `{{ compiler('cxx') }}` at the top level.

**Comment by minrk** [comment]
That didn't work.

Conda-smithy can't handle multiple outputs in general.

I really think multiple outputs are the way to go for several things (I'm mostly looking at mpi variant builds), but 

I'd change this Issue to be in general "conda-smithy doesn't support multiple outputs", at least if variant sources and pin_run_as_build should affect any output other than the main one.

**Comment by SylvainCorlay** [comment]
> I'd change this Issue to be in general "conda-smithy doesn't support multiple outputs", at least if variant sources and pin_run_as_build should affect any output other than the main one.

Done, I just renamed the issue.

**Comment by dougalsutherland** [comment]
> I think in general, conda-smithy rendering doesn't find anything used in subpackages. It doesn't, for instance, correctly find pin_run_as_build fields.

@minrk, I'm not super familiar with all of this but what does conda-smithy do with `pin_run_as_build` in any case? Just trying to get a sense of the things that need to be fixed.

**Comment by minrk** [comment]
I'm working on putting together some sample recipes to better diagnose it. So far, I think it's ignoring the results from outputs other than the one matching the package name, effectively producing the same result as if there were only the one output. If all variants and pinnings happen to occur in the main output, I think the result will be correct.

**Comment by minrk** [comment]
Here's an example recipe:

```
# meta.yaml
package:
  name: my-pkg
  version: 0.1

build:
  number: 0
  script: touch $PREFIX/my-pkg

outputs:
  - name: my-pkg
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - metis
      run:
        - metis
  - name: my-pkg-mpi
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ mpi }}  # [mpi]
        - parmetis
      run:
        - {{ mpi }}  # [mpi]
        - parmetis
```

```
# conda_build_config.yaml
mpi:
  - openmpi  # [not win]
  - mpich  # [not win]

pin_run_as_build:
  mpich:
    max_pin: x.x
  openmpi:
    max_pin: x.x
  metis:
    max_pin: x.x.x
  parmetis:
    max_pin: x.x.x
```

There are two mpi variants, but it only builds one config:

```
# linux_.yaml
c_compiler:
- toolchain_c
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- toolchain_cxx
docker_image:
- condaforge/linux-anvil
metis:
- '5.1'
mpi:
- mpich
- openmpi
pin_run_as_build:
  metis:
    max_pin: x.x.x
```

This *does* seem to build every variant, but with only one job instead of two (that's probably okay), because there is actually only one variant of the first output. What's less okay is lacking the pin_run_as_build for the pkg-mpi output.
