### ISSUE TITLE
.ci_support doesn't add custom channels or custom target

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-smithy#935]
if you add custom targets or channels to conda-forge.yaml file as such:

```
channels:
  sources:
    - mychannel
    - conda-forge
    - defaults
  targets:
    - [mychannel, main]

github:
  user_or_org: 'myorg'
  branch_name: 'mine'
```

They don't seem to get passed onto the files in `.ci_support/linux_.yaml`. 

I mostly tracked it down to:
```
def dump_subspace_config_files(metas, root_path, platform)
```
and 
```
def _collapse_subpackage_variants(list_of_metas):
```
Which doesn't seem to take as input `forge_config` which parses the `conda-forge.yaml` file and updates the default values.

**Comment by hmaarrfk** [comment]
The following patch seems to make things work for me.
```patch
diff --git a/conda_smithy/configure_feedstock.py b/conda_smithy/configure_feedstock.py
index 438ed7d..9fa516b 100755
--- a/conda_smithy/configure_feedstock.py
+++ b/conda_smithy/configure_feedstock.py
@@ -298,6 +298,12 @@ def _collapse_subpackage_variants(list_of_metas):
     _trim_unused_zip_keys(used_key_values)
     _trim_unused_pin_run_as_build(used_key_values)
 
+    # EDIT: TODO
+    # Update the config with any items that are overwritten in the forge config
+    for k, v in forge_config.items():
+        if k in used_key_values:
+            used_key_values[k] = v
+
     return break_up_top_level_values(top_level_loop_vars, used_key_values), top_level_loop_vars
```
If such a feature is welcome, I'll try to write up some tests for it.

**Comment by mjscosta** [comment]
Hi @hmaarrfk ,

I might just bumped into that issue ...

**Comment by k-dominik** [comment]
would definitely like to see this feature as well!

**Comment by isuruf** [comment]
This was replaced with conda_build_config.yaml without notice. We'll try to have better release notes. Btw, there's a bug fixed in #934 for the conda_build_config

**Comment by k-dominik** [comment]
Hey @isuruf, thank you for the update! So does one just place a code block like this in `cbc.yaml`?

```yaml
channels:
  sources:
    - mychannel1
    - mychannel2
    - conda-forge
    - defaults
```
